"""
Generic CDM Model Schema Synchronization and Rebuilding.

This module provides fully generic utilities to repair Pydantic v2 model definitions
generated by Rune for FINOS CDM. It resolves forward references dynamically against
the CDM bundle namespace and restores degenerated NoneType inheritance fields across
all subclasses automatically, eliminating the need for hardcoded type annotations.
"""

from __future__ import annotations

import inspect
import logging
from typing import Any, Dict, List, Optional, Set, Type

from pydantic import BaseModel
from rune.runtime.base_data_class import BaseDataClass

logger = logging.getLogger(__name__)

_MODELS_REBUILT = False


def get_bundle_namespace() -> Dict[str, Any]:
    """Retrieves the full type dictionary of finos._bundle if available."""
    try:
        import finos._bundle
        return finos._bundle.__dict__
    except ImportError:
        return {}


def sync_parent_fields(cls: Type[BaseModel]) -> bool:
    """
    Inspects all base classes in `cls.__mro__`. For any base class that is a BaseModel
    (excluding root BaseModel and BaseDataClass), restores any fields that degenerated
    into NoneType annotations in the subclass.

    Parameters:
        cls: The Pydantic model subclass to repair.

    Returns:
        bool: True if fields were synced or updated.
    """
    if not issubclass(cls, BaseModel) or cls in (BaseModel, BaseDataClass):
        return False

    updated = False
    for base in cls.__mro__[1:]:
        if issubclass(base, BaseModel) and base not in (BaseModel, BaseDataClass) and hasattr(base, "model_fields"):
            for field_name, field_info in base.model_fields.items():
                child_field = cls.model_fields.get(field_name)
                # If field is missing or its annotation resolved to NoneType / None
                if child_field is None or child_field.annotation in (None, type(None)):
                    cls.model_fields[field_name] = field_info
                    updated = True
                    logger.debug(
                        "Synced field '%s' from parent '%s' to child '%s'",
                        field_name,
                        base.__name__,
                        cls.__name__,
                    )
    return updated


def rebuild_cdm_model(
    cls: Type[BaseModel],
    force: bool = True,
    types_namespace: Optional[Dict[str, Any]] = None,
) -> None:
    """
    Generically repairs and rebuilds any FINOS CDM Pydantic model.

    1. Automatically synchronizes inherited fields from parent classes in MRO.
    2. Resolves forward references using the CDM bundle namespace.
    3. Rebuilds Pydantic v2 core schema.

    Parameters:
        cls: The model class to rebuild.
        force: Whether to force rebuilding core validator schemas.
        types_namespace: Optional dictionary of types. Defaults to finos._bundle.__dict__.
    """
    if not issubclass(cls, BaseModel) or cls in (BaseModel, BaseDataClass):
        return

    if types_namespace is None:
        types_namespace = get_bundle_namespace()

    # 1. Sync parent fields from MRO
    sync_parent_fields(cls)

    # 2. Rebuild Pydantic schema
    cls.model_rebuild(force=force, _types_namespace=types_namespace)
    logger.debug("Successfully rebuilt model '%s'", cls.__name__)


def rebuild_cdm_models(*classes: Type[BaseModel]) -> None:
    """
    Rebuilds multiple CDM models.

    Parameters:
        *classes: Variable list of BaseModel subclasses to rebuild.
    """
    for cls in classes:
        rebuild_cdm_model(cls)


def rebuild_all_cdm_models() -> int:
    """
    Discovers and rebuilds all CDM model classes across the entire finos._bundle.
    Fully generic: repairs all 180+ CDM models with zero hardcoded model names.

    Returns:
        int: Number of rebuilt CDM models.
    """
    try:
        import finos._bundle
    except ImportError:
        logger.warning("finos._bundle could not be imported; skipping bulk rebuild.")
        return 0

    rebuilt_count = 0
    ns = finos._bundle.__dict__
    for name in dir(finos._bundle):
        obj = getattr(finos._bundle, name)
        if inspect.isclass(obj) and issubclass(obj, BaseModel) and obj not in (BaseModel, BaseDataClass):
            rebuild_cdm_model(obj, types_namespace=ns)
            rebuilt_count += 1

    logger.debug("Rebuilt %d CDM models across finos._bundle.", rebuilt_count)
    return rebuilt_count


def rebuild_standard_models() -> bool:
    """
    Rebuilds all CDM models across the workspace.
    Safe and idempotent.

    Returns:
        bool: True if models were rebuilt, False if already rebuilt.
    """
    global _MODELS_REBUILT
    if _MODELS_REBUILT:
        return False

    count = rebuild_all_cdm_models()
    _MODELS_REBUILT = True
    return count > 0
